tasks:
  - name: docker
    command: |
      docker-compose up
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
      AWS_ACCESS_KEY_ID: myaccesskey
      AWS_SECRET_ACCESS_KEY: mysecretkey
      AWS_DEFAULT_REGION: us-east-1
    init: |
      cd /workspace
      curl -fSsl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip -qq awscliv2.zip
      sudo ./aws/install --update
      rm awscliv2.zip
      cd $THEIA_WORKSPACE_ROOT
  - name: postgres
    init: |
      curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc|sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
      echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list
      sudo apt update
      sudo apt install -y postgresql-client-13 libpq-dev
vscode:
  extensions:
    - 42Crunch.vscode-openapi
    - amazonwebservices.aws-toolkit-vscode
    - cweijan.vscode-postgresql-client2
